/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoaula.view;

/**
 *
 * @author aylee
 */
public class agendarCita extends javax.swing.JFrame {

    /**
     * Creates new form agendar
     */
    public agendarCita() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        comboEdad = new javax.swing.JComboBox<>();
        comboMotivo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        agendarCita = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtMascota = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        fechas = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        comboEdad1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 3, 50)); // NOI18N
        jLabel1.setText("AGENDAR CONSULTAS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 220, 30));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel4.setText("Nro de telefono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 180, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel6.setText("Ingrese su apellido:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        txtApellido.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 220, 30));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel7.setText("Seleccione la edad de su mascota:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel8.setText("Seleccione que tipo de animal es:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel9.setText("Motivo de la consulta");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, -1));

        comboTipo.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------------------", "Perro", "Gato", "Hamster", "Otro..." }));
        jPanel1.add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 210, 30));

        comboEdad.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        comboEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------------------------------", "" }));
        comboEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEdadActionPerformed(evt);
            }
        });
        jPanel1.add(comboEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 280, 30));

        comboMotivo.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        comboMotivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------------------------------------------", "Consulta - $40.000", "Vacunacion - $80.000", "Esterilizacion - $170.000", "Examenes de laboratorio - $20.000-$50.000", "Peluqueria y baño - $45.000" }));
        jPanel1.add(comboMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aylen 100 x 100.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 100, -1));

        agendarCita.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        agendarCita.setText("AGENDAR");
        agendarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendarCitaActionPerformed(evt);
            }
        });
        jPanel1.add(agendarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 680, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel11.setText("CLINICA ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel12.setText("VETERINARIA");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel13.setText("ANIMALSLOVE");
        jLabel13.setToolTipText("");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel5.setText("Nro de documento:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 180, -1));

        txtDocumento.setEditable(false);
        txtDocumento.setBackground(new java.awt.Color(255, 255, 255));
        txtDocumento.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 220, 30));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel15.setText("Seleccione la fecha para la consulta:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel16.setText("Nombre del dueño:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, -1));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 220, 30));

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel17.setText("Ingrese el nombre de su mascota:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 310, -1));

        txtMascota.setEditable(false);
        txtMascota.setBackground(new java.awt.Color(255, 255, 255));
        txtMascota.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel1.add(txtMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, 220, 30));

        jToggleButton1.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jToggleButton1.setText("Regresar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, -1, -1));
        jPanel1.add(fechas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 270, 30));

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel18.setText("Veterinario:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 180, -1));

        comboEdad1.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        comboEdad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------------------------", "1 año", "2 años", "3 años", "4 años", "5 años", "6 o más años" }));
        comboEdad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEdad1ActionPerformed(evt);
            }
        });
        jPanel1.add(comboEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 210, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/huellitas7.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 740));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEdadActionPerformed

    private void agendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendarCitaActionPerformed
        // TODO add your handling code here:
        
        
        
       
       
        
    }//GEN-LAST:event_agendarCitaActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        login regreso = new login();
        regreso.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void comboEdad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEdad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEdad1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agendarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agendarCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton agendarCita;
    private javax.swing.JComboBox<String> comboEdad;
    private javax.swing.JComboBox<String> comboEdad1;
    private javax.swing.JComboBox<String> comboMotivo;
    private javax.swing.JComboBox<String> comboTipo;
    private com.toedter.calendar.JDateChooser fechas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtMascota;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
