/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoaula.view;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectoaula.model.trabajadores;
import proyectoaula.model.trabajadoresDAO;

/**
 *
 * @author aylee
 */
public class inicioAdmin extends javax.swing.JFrame {

    /**
     * Creates new form inicioAdmin
     */
    public inicioAdmin() {
        initComponents();
        cargarTrabajadoresEnTabla();
        iniciarOpciones();
    }
    public void cargarTrabajadoresEnTabla() {
        trabajadoresDAO trabajadorDAO = new trabajadoresDAO();
        List<trabajadores> listaTrabajadores = trabajadorDAO.obtenerTrabajadores();

        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0); 

        for (trabajadores trabajador : listaTrabajadores) {
            model.addRow(new Object[]{
                trabajador.getIdentificacion(),
                trabajador.getNombre(),
                trabajador.getApellidos(),
                trabajador.getEdad(),
                trabajador.getCargo(),
                trabajador.getTelefono(),
                trabajador.getUser(),
                trabajador.getContraseña(),
               
            });
        }
     }
    
    //OPCIONES MENU ELIMINAR
       public void iniciarOpciones() {
        JMenuItem open = new JMenuItem("Mas Info");
        JMenuItem editar = new JMenuItem("Editar");
        JMenuItem eliminar = new JMenuItem("Despedir");
        
        ppMenuTabla.add(open);
        ppMenuTabla.add(editar);
        ppMenuTabla.add(eliminar);

        table.setComponentPopupMenu(ppMenuTabla);

       
        eliminar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int selectedRow = table.getSelectedRow();

                if (selectedRow != -1) { 
                    
                    String identificacion = (String) table.getValueAt(selectedRow, 0);

                    
                    int confirm = JOptionPane.showConfirmDialog(null, "seguro de que deseas eliminar al trabajador?", "Confirmación", JOptionPane.YES_NO_OPTION);
                    if (confirm == JOptionPane.YES_OPTION) {
                       
                        trabajadoresDAO trabajadoresDAO = new trabajadoresDAO();
                        trabajadoresDAO.eliminarTrabajador(identificacion);

                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Seleccione un trabajador para eliminar.");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ppMenuTabla = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator45 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator43 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator41 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator42 = new javax.swing.JSeparator();
        jSeparator44 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        edad = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        documento = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jPanel18 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jTextField6 = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jPanel20 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jTextField8 = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel16 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jTextField4 = new javax.swing.JTextField();
        jSeparator35 = new javax.swing.JSeparator();
        jLabel43 = new javax.swing.JLabel();
        comboCargo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        jSeparator36 = new javax.swing.JSeparator();
        telefono = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        txtApellidos = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jPanel22 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jTextField9 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        jPanel23 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        jTextField11 = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        jTextField12 = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jSeparator28 = new javax.swing.JSeparator();
        jTextField13 = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jSeparator29 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        jSeparator30 = new javax.swing.JSeparator();
        jTextField14 = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jSeparator31 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jSeparator32 = new javax.swing.JSeparator();
        jTextField15 = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator33 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jSeparator34 = new javax.swing.JSeparator();
        jTextField16 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jSeparator37 = new javax.swing.JSeparator();
        txtUsuario = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jSeparator38 = new javax.swing.JSeparator();
        passContraseña = new javax.swing.JTextField();
        contratar = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 6, -1, -1));

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel1.setText("Veterinaria");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 110, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aylen 100 x 100.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel3.setText("Animalslove");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel4.setText("Clinica");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 20));

        jPanel5.setBackground(new java.awt.Color(153, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel6.setText("Clientes");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 12, 60, 20));

        jSeparator45.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator45.setForeground(new java.awt.Color(0, 0, 0));
        jPanel5.add(jSeparator45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 10));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 220, 40));

        jPanel6.setBackground(new java.awt.Color(153, 255, 255));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel7.setText("Contratos");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, 20));

        jSeparator43.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator43.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jSeparator43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 10));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, 40));

        jPanel7.setBackground(new java.awt.Color(153, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel8.setText("Configuraciones");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 20));

        jSeparator41.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator41.setForeground(new java.awt.Color(0, 0, 0));
        jPanel7.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 10));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 220, 40));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Empleados");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 67, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel10.setText("Empleados");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jSeparator42.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator42.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 10));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 220, 40));

        jSeparator44.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator44.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jSeparator44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 220, 10));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 510));

        jPanel8.setBackground(new java.awt.Color(153, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 3, 36)); // NOI18N
        jLabel9.setText("Administrador");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 41, 200, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel8.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 500));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel8.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 200, 10));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 980, 110));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        table.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Identificacion", "Nombre", "Apellido", "Edad", "Cargo", "Telefono", "Usuario", "Contraseña"
            }
        ));
        jScrollPane1.setViewportView(table);

        jToggleButton1.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jToggleButton1.setText("Actualizar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 839, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("tab1", jPanel10);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel11.setText("Contratar empleado");
        jPanel12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel12.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel13.setText("Contratar empleado");
        jPanel14.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel14.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel12.setText("Edad:*");
        jPanel14.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel14.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 40, 10));

        edad.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel14.add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 200, -1));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel20.setText("Nro de documento:*");
        jPanel14.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jSeparator12.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));
        jPanel14.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, 10));

        documento.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel14.add(documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, -1));

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel19.setText("Contratar empleado");
        jPanel17.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator11.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel17.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel21.setText("Contratar empleado");
        jPanel18.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator13.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel18.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel22.setText("Nombre:*");
        jPanel18.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jSeparator14.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jPanel18.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 10));

        jTextField6.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel18.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, -1));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel23.setText("Contratar empleado");
        jPanel19.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator15.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator15.setForeground(new java.awt.Color(0, 0, 0));
        jPanel19.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel25.setText("Contratar empleado");
        jPanel20.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator17.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator17.setForeground(new java.awt.Color(0, 0, 0));
        jPanel20.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jLabel26.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel26.setText("Nombre:*");
        jPanel20.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jSeparator18.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator18.setForeground(new java.awt.Color(0, 0, 0));
        jPanel20.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 10));

        jTextField8.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel20.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, -1));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel15.setText("Contratar empleado");
        jPanel15.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel15.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel17.setText("Contratar empleado");
        jPanel16.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator9.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        jPanel16.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel18.setText("Nombre:*");
        jPanel16.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jSeparator10.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        jPanel16.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 10));

        jTextField4.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel16.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, -1));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator35.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator35.setForeground(new java.awt.Color(0, 0, 0));
        jPanel15.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 50, 10));

        jLabel43.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel43.setText("Cargo:*");
        jPanel15.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        comboCargo.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        comboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------------------------", "Veterinario", "Vacunacion", "Cirujano", "Bacteriologo", "Peluquero", "" }));
        jPanel15.add(comboCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 200, 30));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel14.setText("Nombre:*");
        jPanel15.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel15.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 60, 10));

        txtNombre.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel15.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, -1));

        jPanel19.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel17.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator36.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator36.setForeground(new java.awt.Color(0, 0, 0));
        jPanel17.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 120, 10));

        telefono.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel17.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 200, -1));

        jLabel44.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel44.setText("Nro de telefono:*");
        jPanel17.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        jSeparator16.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        jPanel17.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 70, 10));

        txtApellidos.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel17.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, -1));

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel24.setText("Apellido:*");
        jPanel17.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jPanel12.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel27.setText("Contratar empleado");
        jPanel21.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator19.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator19.setForeground(new java.awt.Color(0, 0, 0));
        jPanel21.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel28.setText("Contratar empleado");
        jPanel22.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator20.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator20.setForeground(new java.awt.Color(0, 0, 0));
        jPanel22.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jLabel29.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel29.setText("Nombre:*");
        jPanel22.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jSeparator21.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator21.setForeground(new java.awt.Color(0, 0, 0));
        jPanel22.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 10));

        jTextField9.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel22.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, -1));

        jLabel30.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel30.setText("Edad:*");
        jPanel22.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        jSeparator22.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator22.setForeground(new java.awt.Color(0, 0, 0));
        jPanel22.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 40, 10));

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel31.setText("Contratar empleado");
        jPanel23.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator23.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator23.setForeground(new java.awt.Color(0, 0, 0));
        jPanel23.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jLabel32.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel32.setText("Apellido:*");
        jPanel23.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jSeparator24.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator24.setForeground(new java.awt.Color(0, 0, 0));
        jPanel23.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 70, 10));

        jTextField11.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel23.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, -1));

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel33.setText("Contratar empleado");
        jPanel24.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator25.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator25.setForeground(new java.awt.Color(0, 0, 0));
        jPanel24.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jLabel34.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel34.setText("Nombre:*");
        jPanel24.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jSeparator26.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator26.setForeground(new java.awt.Color(0, 0, 0));
        jPanel24.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 10));

        jTextField12.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel24.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, -1));

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel21.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel35.setText("Contratar empleado");
        jPanel25.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator27.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator27.setForeground(new java.awt.Color(0, 0, 0));
        jPanel25.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jLabel36.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel36.setText("Nro de documento:*");
        jPanel25.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jSeparator28.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator28.setForeground(new java.awt.Color(0, 0, 0));
        jPanel25.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 10));

        jTextField13.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel25.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, -1));

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel37.setText("Contratar empleado");
        jPanel26.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator29.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator29.setForeground(new java.awt.Color(0, 0, 0));
        jPanel26.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jLabel38.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel38.setText("Nombre:*");
        jPanel26.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jSeparator30.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator30.setForeground(new java.awt.Color(0, 0, 0));
        jPanel26.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 10));

        jTextField14.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel26.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, -1));

        jPanel25.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel39.setText("Contratar empleado");
        jPanel27.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator31.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator31.setForeground(new java.awt.Color(0, 0, 0));
        jPanel27.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jLabel40.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel40.setText("Apellido:*");
        jPanel27.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jSeparator32.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator32.setForeground(new java.awt.Color(0, 0, 0));
        jPanel27.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 70, 10));

        jTextField15.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel27.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, -1));

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        jLabel41.setText("Contratar empleado");
        jPanel28.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        jSeparator33.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator33.setForeground(new java.awt.Color(0, 0, 0));
        jPanel28.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 10));

        jLabel42.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel42.setText("Nombre:*");
        jPanel28.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jSeparator34.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator34.setForeground(new java.awt.Color(0, 0, 0));
        jPanel28.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 10));

        jTextField16.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel28.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, -1));

        jPanel27.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel25.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel21.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel12.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel45.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel45.setText("Usuario:*");
        jPanel12.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        jSeparator37.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator37.setForeground(new java.awt.Color(0, 0, 0));
        jPanel12.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 60, 10));

        txtUsuario.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel12.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 200, -1));

        jLabel46.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        jLabel46.setText("Contraseña:*");
        jPanel12.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        jSeparator38.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator38.setForeground(new java.awt.Color(0, 0, 0));
        jPanel12.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 90, 10));

        passContraseña.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel12.add(passContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 200, -1));

        contratar.setFont(new java.awt.Font("Tw Cen MT", 3, 18)); // NOI18N
        contratar.setText("Contratar");
        contratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarActionPerformed(evt);
            }
        });
        jPanel12.add(contratar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        jTabbedPane6.addTab("tab2", jPanel12);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 980, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 365, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("tab3", jPanel1);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 980, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 365, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("tab4", jPanel9);

        getContentPane().add(jTabbedPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 980, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarActionPerformed
        String identificacion = documento.getText();
        String nombre = txtNombre.getText();
        String apellidos = txtApellidos.getText();
        String edades = edad.getText();
        String cargo = (String) comboCargo.getSelectedItem();
        String telefonos = telefono.getText();
        String usuario = txtUsuario.getText();
        String contraseña = passContraseña.getText();

        if (identificacion.isEmpty() || nombre.isEmpty() || apellidos.isEmpty() || edades.isEmpty()|| cargo.isEmpty() || telefonos.isEmpty() || usuario.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            trabajadoresDAO trabajadorDAO = new trabajadoresDAO();

            //LocalDate fechaContratacion = LocalDate.now();

            trabajadorDAO.contratarTrabajador( identificacion, nombre, apellidos, edades, cargo, telefonos, usuario, contraseña);

            JOptionPane.showMessageDialog(this, "Trabajador contratado exitosamente", "Exito", JOptionPane.INFORMATION_MESSAGE);

            //limpiarCampos();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error al contratar al trabajador: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_contratarActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        cargarTrabajadoresEnTabla();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        jTabbedPane6.setSelectedIndex(0);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        jTabbedPane6.setSelectedIndex(1);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
        jPanel2.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jPanel2MouseMoved

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        jPanel2.setBackground(new Color(153,255,255));
    }//GEN-LAST:event_jPanel2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicioAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicioAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboCargo;
    private javax.swing.JToggleButton contratar;
    private javax.swing.JTextField documento;
    private javax.swing.JTextField edad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField passContraseña;
    private javax.swing.JPopupMenu ppMenuTabla;
    private javax.swing.JTable table;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
