/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoaula.view;

import javax.swing.JOptionPane;
import proyectoaula.model.UsuarioDAO;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author aylee
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        documento2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        documento3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ingresar = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        txtpassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        crearCuenta = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 3, 20)); // NOI18N
        jLabel2.setText("VET ANIMALSLOVE");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 200, -1));

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 3, 20)); // NOI18N
        jLabel5.setText("VET ANIMALSLOVE");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 200, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 2, 17)); // NOI18N
        jLabel6.setText("Ingrese su documento de identidad:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));
        jPanel3.add(documento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 90, 180, 30));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 2, 17)); // NOI18N
        jLabel7.setText("Ingrese el nombre de su mascota:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));
        jPanel3.add(documento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 180, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 280, 360));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 2, 17)); // NOI18N
        jLabel8.setText("Ingrese su contraseña:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        ingresar.setFont(new java.awt.Font("Tw Cen MT", 2, 17)); // NOI18N
        ingresar.setText("INGRESAR");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        jPanel2.add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 2, 17)); // NOI18N
        jLabel10.setText("Ingrese su usuario:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        txtuser.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel2.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 180, 30));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 2, 17)); // NOI18N
        jLabel11.setText("Seleccione su rol:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        jComboBox2.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------------------", "Administrador", "Personal", "Cliente" }));
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 30));

        txtpassword.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 180, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 280, 360));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 3, 17)); // NOI18N
        jLabel9.setText("No tiene cuenta?");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen4.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 710, 440));

        crearCuenta.setFont(new java.awt.Font("Tw Cen MT", 2, 17)); // NOI18N
        crearCuenta.setText("Crear cuenta");
        jPanel1.add(crearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        String username = txtuser.getText();
        String password = new String(txtpassword.getPassword());

        UsuarioDAO userDao = new UsuarioDAO();

        boolean isAuthenticated = userDao.authenticateUser(username, password);
        UIManager.put("OptionPane.messageForeground", Color.RED);
        UIManager.put("OptionPane.messageFont", new Font("Tw Cent MT", Font.BOLD, 18));
        ImageIcon icon = new ImageIcon("proyectoaula.model/imagenes/trabajando.png");

        if (isAuthenticated) {
            JOptionPane.showMessageDialog(null, "Login exitoso", "Exito",JOptionPane.INFORMATION_MESSAGE, icon);
            inicioAdmin dashboard = new inicioAdmin();
            dashboard.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrecta", "Error de Login", JOptionPane.ERROR_MESSAGE, icon);
        }
    }//GEN-LAST:event_ingresarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton crearCuenta;
    private javax.swing.JTextField documento2;
    private javax.swing.JTextField documento3;
    private javax.swing.JToggleButton ingresar;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
